import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import CartProduct from '../../components/CartProduct';

const Cart = () => (
    <div>
        <Head>
            <title>SellBee | Your Cart</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex mt-10 gap-14 mb-14 mx-p-w">
            <div className="flex flex-col flex-1 gap-3">
                <div
                    className="flex items-center py-4 pl-4 mb-3 border rounded-md pr-9"
                    style={{ borderColor: '#D4D4D4' }}
                >
                    <input type="checkbox" className="cursor-pointer" />

                    <span
                        style={{ fontSize: 8 }}
                        className="flex-1 ml-5 font-black tracking-wide font-lato"
                    >
                        Select All
                    </span>

                    <span
                        className="pr-5 mr-5 font-black tracking-wide uppercase border-r cursor-pointer font-lato text-bg-primary"
                        style={{ fontSize: 8, borderColor: '#EDEDED' }}
                    >
                        update cart
                    </span>

                    <span
                        className="font-black tracking-wide uppercase cursor-pointer font-lato"
                        style={{ fontSize: 8, color: '#FF0000' }}
                    >
                        remove
                    </span>
                </div>

                <CartProduct selected />

                <CartProduct />
            </div>

            <div className="flex flex-col gap-5" style={{ maxHeight: 247 }}>
                <div
                    style={{ backgroundColor: '#FFF7F3', borderColor: '#A1E887' }}
                    className="flex items-center w-64 gap-4 py-4 pl-5 border rounded-md cursor-pointer pr-7"
                >
                    <span>
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="18.5"
                            height="12.001"
                            viewBox="0 0 18.5 12.001"
                        >
                            <path
                                id="Vector"
                                d="M4945.458,199h-15.416a1.524,1.524,0,0,1-1.542-1.5v-3a1.5,1.5,0,1,0,0-3v-3a1.523,1.523,0,0,1,1.542-1.5h15.416a1.523,1.523,0,0,1,1.542,1.5v3a1.5,1.5,0,1,0,0,3v3A1.524,1.524,0,0,1,4945.458,199Zm-13.1-10a.761.761,0,0,0-.771.75v6.5a.761.761,0,0,0,.771.75h10.792a.761.761,0,0,0,.771-.75v-6.5a.761.761,0,0,0-.771-.75Zm10.536,7h-10.28v-6h10.28v6Z"
                                transform="translate(-4928.5 -187)"
                                fill="#493548"
                            />
                        </svg>
                    </span>
                    <span
                        className="flex-1 font-semibold font-poppins text-bg-primary"
                        style={{ fontSize: 9 }}
                    >
                        I have promo code
                    </span>
                    <span>
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="3.548"
                            height="7.096"
                            viewBox="0 0 3.548 7.096"
                        >
                            <path
                                id="Rectangle_2"
                                data-name="Rectangle 2"
                                d="M5139.548,196.644v-7.1l3.548,3.548Z"
                                transform="translate(-5139.548 -189.548)"
                                fill="#493548"
                            />
                        </svg>
                    </span>
                </div>

                <div className="flex flex-col gap-5 px-5 py-4 border rounded-md">
                    <span className="font-semibold font-poppins" style={{ fontSize: 10 }}>
                        Shopping Summary
                    </span>

                    <div className="flex items-center justify-between">
                        <span className="font-medium font-poppins" style={{ fontSize: 9 }}>
                            Total
                        </span>
                        <span className="text-sm font-semibold text-bg-primary font-poppins">
                            1,952.66
                        </span>
                    </div>

                    <Link href="/checkout">
                        <button
                            type="button"
                            className="px-20 py-3 font-bold uppercase rounded-md bg-bg-primary font-lato"
                            style={{ fontSize: 10, color: '#FBFBFB' }}
                        >
                            checkout
                        </button>
                    </Link>

                    <span
                        className="self-center font-bold cursor-pointer font-lato text-bg-primary hover:underline"
                        style={{ fontSize: 8 }}
                    >
                        Back to Shopping
                    </span>
                </div>
            </div>
        </main>
    </div>
);

export default Cart;
