import ExpandLess from '@mui/icons-material/ExpandLess';
import ExpandMore from '@mui/icons-material/ExpandMore';
import Box from '@mui/material/Box';
import Collapse from '@mui/material/Collapse';
import FormControl from '@mui/material/FormControl';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import Select from '@mui/material/Select';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import CategorizedProducts from '../../components/CategorizedProducts';
import ImageSlider from '../../components/ImageSlider';
import OnSale from '../../components/OnSale';
import RangeSlider from '../../components/RangeSlider';

const Category: NextPage = () => {
    const router = useRouter();
    const { categoryTitle } = router.query;

    console.log(categoryTitle);

    const [openCategory, setOpenCategory] = useState(false);
    const [openCategoryIndex, setOpenCategoryIndex] = useState(-1);
    const [brand, setBrand] = useState('');
    const [location, setLocation] = useState('');

    const categories = [
        {
            name: 'Laptop & Computer',
            stock: 45,
            subCategories: [
                {
                    name: 'Hardware',
                    stock: 25,
                },
                {
                    name: 'Laptop',
                    stock: 25,
                },
                {
                    name: 'Memory',
                    stock: 25,
                },
                {
                    name: 'Storage',
                    stock: 25,
                },
                {
                    name: 'Software',
                    stock: 25,
                },
            ],
        },
    ];

    const colors = ['white', 'black', 'blue', 'red'];

    const handleClick = (index: number) => {
        setOpenCategory((prev) => !prev);
        setOpenCategoryIndex(index);
    };

    return (
        <div>
            <Head>
                <title>SellBee | {categoryTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mt-10">
                <div className="flex justify-between mb-24 mx-p-w">
                    {/* left */}
                    <div className="flex flex-col gap-12 w-60">
                        {/* categories */}
                        <div
                            className="flex flex-col py-6 overflow-auto border gap-7 rounded-2xl"
                            style={{ height: 242, borderColor: '#C4C4C4' }}
                        >
                            <span className="px-5 text-sm font-semibold font-poppins">
                                Show all categories
                            </span>

                            <div className="flex flex-col gap-3 px-7">
                                {categories.map((category, index) => (
                                    <div key={category.name}>
                                        <button
                                            type="button"
                                            className="flex items-center justify-between w-full"
                                            onClick={() => handleClick(index)}
                                        >
                                            <span
                                                className="font-semibold font-lato"
                                                style={{ fontSize: 9 }}
                                            >
                                                {category.name}
                                            </span>
                                            {openCategory && openCategoryIndex === index ? (
                                                <ExpandLess sx={{ fontSize: 12 }} />
                                            ) : (
                                                <ExpandMore sx={{ fontSize: 12 }} />
                                            )}
                                        </button>
                                        <Collapse
                                            in={openCategory && openCategoryIndex === index}
                                            timeout="auto"
                                            unmountOnExit
                                        >
                                            <div className="flex flex-col gap-1 mt-2 ml-5">
                                                {category.subCategories.map((subCategory) => (
                                                    <div
                                                        key={subCategory.name}
                                                        className="font-normal font-lato"
                                                        style={{ fontSize: 9 }}
                                                    >
                                                        {subCategory.name}
                                                    </div>
                                                ))}
                                            </div>
                                        </Collapse>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* filters */}
                        <div className="flex flex-col gap-7">
                            <span className="text-base font-semibold tracking-wide font-poppins">
                                Filters
                            </span>

                            <div className="flex flex-col gap-2">
                                <span
                                    className="font-semibold tracking-wide font-lato"
                                    style={{ fontSize: 10, color: '#575757' }}
                                >
                                    Price range
                                </span>

                                <RangeSlider />
                            </div>

                            <div className="flex flex-col gap-4">
                                <Box>
                                    <FormControl fullWidth size="small">
                                        <InputLabel
                                            sx={{
                                                fontSize: 9,
                                                height: '55%',
                                                display: 'flex',
                                                alignItems: 'center',
                                            }}
                                            className="tracking-wide"
                                        >
                                            Choose Brand
                                        </InputLabel>
                                        <Select
                                            value={brand}
                                            label="Choose Brand"
                                            onChange={(e) => setBrand(e.target.value)}
                                        >
                                            <MenuItem value="easy">Easy</MenuItem>
                                            <MenuItem value="infinity">Infinity</MenuItem>
                                            <MenuItem value="cats-eye">Cats-Eye</MenuItem>
                                        </Select>
                                    </FormControl>
                                </Box>

                                <Box>
                                    <FormControl fullWidth size="small">
                                        <InputLabel
                                            sx={{
                                                fontSize: 9,
                                                height: '55%',
                                                display: 'flex',
                                                alignItems: 'center',
                                            }}
                                            className="tracking-wide"
                                        >
                                            Choose Loaction
                                        </InputLabel>
                                        <Select
                                            value={location}
                                            label="Choose Loaction"
                                            onChange={(e) => setLocation(e.target.value)}
                                        >
                                            <MenuItem value="uttara">Uttara</MenuItem>
                                            <MenuItem value="gulshan">Gulshan</MenuItem>
                                            <MenuItem value="banani">Banani</MenuItem>
                                        </Select>
                                    </FormControl>
                                </Box>
                            </div>

                            <div>
                                <div className="flex justify-between">
                                    <span
                                        style={{ color: '#575757', fontSize: 11 }}
                                        className="font-semibold tracking-wide font-lato"
                                    >
                                        Color
                                    </span>
                                    <button type="button" className="flex items-center gap-1">
                                        <svg
                                            xmlns="http://www.w3.org/2000/svg"
                                            width="10.499"
                                            height="10"
                                            viewBox="0 0 10.499 10"
                                        >
                                            <path
                                                id="Vector"
                                                d="M2346.5,697.25a5.006,5.006,0,1,1,5.25-5A5.135,5.135,0,0,1,2346.5,697.25Zm-2.447-5.479a.313.313,0,0,0-.228.1l-.456.479a.351.351,0,0,0,0,.479l2.1,2.2a.311.311,0,0,0,.455,0l3.71-3.9a.351.351,0,0,0,0-.479l-.456-.479a.312.312,0,0,0-.456,0l-3.025,3.176-1.412-1.482A.314.314,0,0,0,2344.053,691.771Z"
                                                transform="translate(-2341.25 -687.25)"
                                                fill="#c4c4c4"
                                            />
                                        </svg>

                                        <span
                                            className="font-semibold tracking-wide font-lato"
                                            style={{ fontSize: 8, color: '#575757' }}
                                        >
                                            Select All
                                        </span>
                                    </button>
                                </div>

                                <div className="grid grid-cols-2 gap-2 pr-12 mt-6 mb-3">
                                    {colors.map((color) => (
                                        <span
                                            key={color}
                                            style={{
                                                height: 26.5,
                                                fontSize: 8,
                                                borderColor: '#A1E887',
                                            }}
                                            className="flex items-center justify-center font-semibold tracking-wide border rounded-md cursor-pointer font-lato text-bg-primary"
                                        >
                                            {color}
                                        </span>
                                    ))}
                                </div>

                                <button
                                    type="button"
                                    className="font-bold tracking-wide font-lato text-bg-primary"
                                    style={{ fontSize: 9 }}
                                >
                                    <span className="hover:underline">+ Show more</span>
                                </button>
                            </div>

                            <div className="flex flex-col">
                                <button
                                    type="button"
                                    className="flex items-center justify-center font-bold tracking-wide text-white uppercase rounded-lg bg-bg-primary font-lato"
                                    style={{ fontSize: 10, height: 33 }}
                                >
                                    filter
                                </button>
                                <button
                                    type="button"
                                    className="flex items-end self-center justify-center font-bold tracking-wide rounded-lg font-lato w-max"
                                    style={{ fontSize: 10, height: 33 }}
                                >
                                    <span className="hover:underline">Reset Filter</span>
                                </button>
                            </div>
                        </div>
                    </div>

                    {/* right */}
                    <div className="w-full overflow-hidden" style={{ maxWidth: '78%' }}>
                        <ImageSlider pageName="all-categories" />
                        <CategorizedProducts categoryTitle="Laptop Products" />
                    </div>
                </div>

                <OnSale />
            </main>
        </div>
    );
};

export default Category;
