import type { NextPage } from 'next';
import Head from 'next/head';
import OnSale from '../components/OnSale';

const AllCategories: NextPage = () => (
    <div>
        <Head>
            <title>SellBee | All Categories</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="mt-10">
            <div className="flex mb-24 mx-p-w gap-9">
                {/* left */}
                <div className="flex flex-col gap-12 bg-red-400 w-60">
                    {/* categories */}
                    <div
                        className="flex flex-col py-6 overflow-auto gap-7 rounded-2xl"
                        style={{ height: 242 }}
                    >
                        <span className="px-5 text-sm font-semibold font-poppins">
                            Show all categories
                        </span>

                        <div className="px-7">categories</div>
                    </div>

                    {/* filters */}
                    <div>f</div>
                </div>

                {/* right */}
                <div className="flex-1 bg-indigo-400">b</div>
            </div>

            <OnSale />
        </main>
    </div>
);

export default AllCategories;
