import type { NextPage } from 'next';
import Head from 'next/head';
import BestDeals from '../components/BestDeals';
import ImageSlider from '../components/ImageSlider';
import Offerings from '../components/Offerings';
import OnSale from '../components/OnSale';
import SpecialOffers from '../components/SpecialOffers';

const Home: NextPage = () => (
    <div>
        <Head>
            <title>SellBee</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="mt-10">
            <ImageSlider />
            {/* <FlashSale /> */}
            <SpecialOffers />
            <BestDeals />
            <Offerings />
            <OnSale />
        </main>
    </div>
);

export default Home;
