import Head from 'next/head';
import React from 'react';

const Checkout = () => (
    <div>
        <Head>
            <title>SellBee | Checkout</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="mt-10 mb-7">checkout</main>
    </div>
);

export default Checkout;
